language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:
  - tylerJPike/OOS

after_success:
  - Rscript -e 'covr::codecov(token = 'eabccb13-c362-4955-9ee2-34cfb28f0c29')'
